<?php

namespace AppBundle\Repository;

/**
 * SongsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongsRepository extends \Doctrine\ORM\EntityRepository
{
}
